name: discord-video-preview

services:
  server:
    build: .
    develop:
      watch:
        - action: rebuild
          path: .

  rclone_webdav:
    image: rclone/rclone:latest
    volumes:
      - ./rclone.conf:/config/rclone/rclone.conf:ro
      - ./_data/rclone_cache:/cache
      - ./_data/rclone_data:/data
    command: >
      serve webdav someremote:/data
      --vfs-cache-mode full
      --cache-dir /cache
      --vfs-fast-fingerprint
      --vfs-cache-max-size 1G
      --fast-list
      --addr 0.0.0.0:8080
    ports:
      - "8080:8080"

  cobalt:
    image: ghcr.io/imputnet/cobalt:11
    init: true
    read_only: true
    ports:
      - "9000:9000"
    environment:
      API_URL: "http://localhost:9000/"

  traces:
    image: ghcr.io/ctrlspice/otel-desktop-viewer:latest-arm64
    ports:
      - "8005:8000"
      - "4317:4317"
