services:
  web:
    image: nginx
    restart: unless-stopped
    ports:
      - "80"
    volumes:
      - preview:/usr/share/nginx/html:ro
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`preview.rcp2.r9n.co`)"
      - "traefik.http.routers.web.rule=entrypoints=websecure"
      - "traefik.http.routers.web.tls.certResolver=letsencrypt"
      - "traefik.http.routers.web.loadbalancer.server.port=80"
  bot:
    build: .
    restart: on-failure:3
    environment:
      PREVIEW_DIR: /preview
      PREVIEW_BASE_URL: "https://preview.rcp2.r9n.co/"
      DISCORD_TOKEN: ${DISCORD_TOKEN}
    depends_on:
      - cobalt-api
    volumes:
      - preview:/preview
  cobalt-api:
    image: ghcr.io/imputnet/cobalt:10
    #read_only: true
    restart: on-failure:3
    expose:
      - "9000"
    environment:
      API_URL: "http://cobalt-api:9000/"

volumes:
  preview:

networks:
  dokploy-network:
    external: true